title: Mathai Sibu Kombasseril # your name (or website title) here
logo: "/images/linkedin.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Business Consultant and Strategist
  <br>
  Founder @ [Around Zero Ltd](https://www.around-zero.com/) <br>
  Passionate about all areas of Data Science and looking to transition as a Data Analyst. Pursuing MSc in Data Science and currently in the final phase of research-thesis. Eager to put my knowledge into practice as a Data Analyst.
  <br><br>
  Previously worked as Business development and team leader for logistics & international freight forwarding, with experience in operations, developing new strategic partnerships, leading cross-functional teams, managing client-relationship, negotiating for new business development, and strategizing for profitable growth.
  <br><br>
  <a href="https://www.linkedin.com/in/mathai-sibu-k-b16965196/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
